apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "fake-rabbit.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "fake-rabbit.name" . }}
    helm.sh/chart: {{ include "fake-rabbit.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fake-rabbit.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fake-rabbit.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-alt
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /hello.txt?name=OK
              port: http-alt
              initialDelaySeconds: 10
              periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /hello.txt?name=OK
              port: http-alt
              initialDelaySeconds: 30
              periodSeconds: 5
          env:
            - name: FAKE_RABBIT_CONFIG
              value: /etc/fake-rabbit/fake-rabbit.conf
          volumeMounts:
            - mountPath: /etc/fake-rabbit
              name: config-file
      volumes:
        - name: config-file
          configMap:
            name: fake-rabbit-config
            items:
              - key: configFile
                # mode: 0444
                path: fake-rabbit.conf
