---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: fake-rabbit-deploy
  labels:
    app.kubernetes.io/name: fake-rabbit
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: fake-rabbit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fake-rabbit
    spec:
      containers:
        - name: fake-rabbit
          image: "909435457203.dkr.ecr.eu-central-1.amazonaws.com/fake-rabbit:latest"
          imagePullPolicy: Always
          ports:
            - name: http-alt
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /hello.txt?name=OK
              port: http-alt
          readinessProbe:
            httpGet:
              path: /hello.txt?name=OK
              port: http-alt
          env:
            - name: FAKE_RABBIT_CONFIG
              value: /etc/fake-rabbit/fake-rabbit.conf
          volumeMounts:
            - mountPath: /etc/fake-rabbit
              name: config-file
          resources:
            limits:
              cpu: 1
              memory: 2048Mi
      volumes:
        - name: config-file
          configMap:
            name: fake-rabbit-config
            items:
              - key: configFile
                path: fake-rabbit.conf
