---
apiVersion: v1
kind: Service
metadata:
  name: fake-rabbit-svc
  labels:
    app.kubernetes.io/name: fake-rabbit
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hello-<my-stack>.pit.sh
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:909435457203:certificate/<my-stack-certificate-uuid>
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http-alt
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: fake-rabbit
